package corbacookie.Cookie;

/**
* corbacookie/Cookie/cookieserverHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from Cookie.idl
* Samstag, 17. November 2012 17:18 Uhr MEZ
*/

public final class cookieserverHolder implements org.omg.CORBA.portable.Streamable
{
  public corbacookie.Cookie.cookieserver value = null;

  public cookieserverHolder ()
  {
  }

  public cookieserverHolder (corbacookie.Cookie.cookieserver initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = corbacookie.Cookie.cookieserverHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    corbacookie.Cookie.cookieserverHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return corbacookie.Cookie.cookieserverHelper.type ();
  }

}
