package corbacookie.Cookie;


/**
* corbacookie/Cookie/cookieserverHelper.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from Cookie.idl
* Samstag, 17. November 2012 17:18 Uhr MEZ
*/

abstract public class cookieserverHelper
{
  private static String  _id = "IDL:corbacookie/Cookie/cookieserver:1.0";

  public static void insert (org.omg.CORBA.Any a, corbacookie.Cookie.cookieserver that)
  {
    org.omg.CORBA.portable.OutputStream out = a.create_output_stream ();
    a.type (type ());
    write (out, that);
    a.read_value (out.create_input_stream (), type ());
  }

  public static corbacookie.Cookie.cookieserver extract (org.omg.CORBA.Any a)
  {
    return read (a.create_input_stream ());
  }

  private static org.omg.CORBA.TypeCode __typeCode = null;
  synchronized public static org.omg.CORBA.TypeCode type ()
  {
    if (__typeCode == null)
    {
      __typeCode = org.omg.CORBA.ORB.init ().create_interface_tc (corbacookie.Cookie.cookieserverHelper.id (), "cookieserver");
    }
    return __typeCode;
  }

  public static String id ()
  {
    return _id;
  }

  public static corbacookie.Cookie.cookieserver read (org.omg.CORBA.portable.InputStream istream)
  {
    return narrow (istream.read_Object (_cookieserverStub.class));
  }

  public static void write (org.omg.CORBA.portable.OutputStream ostream, corbacookie.Cookie.cookieserver value)
  {
    ostream.write_Object ((org.omg.CORBA.Object) value);
  }

  public static corbacookie.Cookie.cookieserver narrow (org.omg.CORBA.Object obj)
  {
    if (obj == null)
      return null;
    else if (obj instanceof corbacookie.Cookie.cookieserver)
      return (corbacookie.Cookie.cookieserver)obj;
    else if (!obj._is_a (id ()))
      throw new org.omg.CORBA.BAD_PARAM ();
    else
    {
      org.omg.CORBA.portable.Delegate delegate = ((org.omg.CORBA.portable.ObjectImpl)obj)._get_delegate ();
      corbacookie.Cookie._cookieserverStub stub = new corbacookie.Cookie._cookieserverStub ();
      stub._set_delegate(delegate);
      return stub;
    }
  }

  public static corbacookie.Cookie.cookieserver unchecked_narrow (org.omg.CORBA.Object obj)
  {
    if (obj == null)
      return null;
    else if (obj instanceof corbacookie.Cookie.cookieserver)
      return (corbacookie.Cookie.cookieserver)obj;
    else
    {
      org.omg.CORBA.portable.Delegate delegate = ((org.omg.CORBA.portable.ObjectImpl)obj)._get_delegate ();
      corbacookie.Cookie._cookieserverStub stub = new corbacookie.Cookie._cookieserverStub ();
      stub._set_delegate(delegate);
      return stub;
    }
  }

}
