package corbacookie.Cookie;


/**
* corbacookie/Cookie/cookieserverOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from Cookie.idl
* Samstag, 17. November 2012 17:18 Uhr MEZ
*/

public interface cookieserverOperations 
{
  String printCookieNum (int i);
  String printCookie ();
} // interface cookieserverOperations
