package corbacookie.Cookie;


/**
* corbacookie/Cookie/cookieserver.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from Cookie.idl
* Samstag, 17. November 2012 17:18 Uhr MEZ
*/

public interface cookieserver extends cookieserverOperations, org.omg.CORBA.Object, org.omg.CORBA.portable.IDLEntity 
{
} // interface cookieserver
